sudo: required
dist: trusty
language: ruby
rvm:
- 2.6.3
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_21c873d1cdfb_key -iv $encrypted_21c873d1cdfb_iv
  -in deploy_key.enc -out ./deploy/deploy_key -d
- gem update --system
- gem install bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- RAILS_ENV=test ./bin/rake db:create
- RAILS_ENV=test ./bin/rake db:migrate
- RAILS_ENV=test ./bin/bundle exec rspec
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 ./deploy/deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy/deploy_key
    $DEPLOY_USER@$DEPLOY_HOST './deploy.sh'
  on:
    branch: fix-deploy
