version: '2'

services:
  setup:
    build: .
    depends_on:
      - 'postgres'
      - 'box'
    command: 
      - 'ls -la'
      # - './bin/rails db:create'
      # - './bin/rails db:migrate'
    volumes_from:
      - box

  postgres:
    image: 'postgres:11.4'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  nginx:
    restart: always
    build: ./nginx
    ports:
      - '80:80'

  backend:
    depends_on:
      - 'postgres'
      - 'setup'
    build: .
    command:
      - bash start.sh
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box
      
volumes:
  postgres:
  box:
